#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Script: pacman_packages.sh
# Descrição: downloads de pacotes essenciais para o meu uso;
# -----------------------------------------------------------------------------
#
# Pacotes que serão instalados
packages=(
    "bash-completion"
    "linux-tools"
    "linux-headers"
    "lsb-release"
    "man-db"
    "man-pages"
    "memtest86+"
    "pacman-contrib"
    "libva-intel-driver"
    "libusb"
    "libev"
    "base-devel"
    "gst-libav"
    "gst-plugins-bad"
    "gst-plugins-base"
    "gst-plugins-good"
    "gst-plugins-ugly"
    "wget"
    "automake"
    "cmake"
    "gcc"
    "go"
    "samba"
    "galculator"
    "gnome-font-viewer"
    "polkit-gnome"
    "wireshark-qt"
    "vlc"
    "ufw"
    "ufw-extras"
    "intel-ucode"
    "linux-firmware"
    "networkmanager"
    "xdg-user-dirs"
    "fzf"
    "virt-manager"
    "tlp"
    "xorg-xbacklight"
    "otf-font-awesome"
    "ttf-font-awesome"
    "qt5ct"
    "curl"
    "ethtool"
    "p7zip"
    "unrar"
    "zip"
    "usbutils"
    "zsh"
    "zsh-autosuggestions"
    "zsh-completions"
    "xorg-server"
    "xorg-xinit"
    "xorg-input"
    "xorg-xrandr"
    "arandr"
    "mesa"
    "mesa-utils"
    "xf86-input-libinput"
    "xf86-input-wacom"
    "xf86-video-intel"
    "lib32-mesa"
    "vulkan-intel"
    "lib32-vulkan-intel"
    "vulkan-icd-loader"
    "lib32-vulkan-icd-loader"
    "bluez"
    "bluez-utils"
    "bluez-firmware"
    "blueman"
    "pulseaudio-bluetooth"
    "pulseaudio-alsa"
    "alsa-utils"
    "alsa-plugins"
    "pavucontrol"
    "htop"
    "gtop"
    "numlockx"
    "sxhkd"
    "speedtest_cli"
    "gparted"
    "aspell"
    "aspell-pt"
    "arc-gtk-theme"
    "papirus-icon-theme"
    "capitaine-cursors"
    "ttf-iosevka-nerd"
    "neofetch"
    "xdotool"
    "dunst"
    "youtube-dl"
    "kitty"
    "rofi"
    "lf"
    "ffmpeg"
    "bat"
    "atool"
    "mediainfo"
    "ffmpegthumbnailer"
    "poppler"
    "ueberzug"
    "zathura"
    "vim"
    "discord"
    "steam"
    "qbittorrent"
    "telegram-desktop"
    "libreoffice-fresh"
    "libreoffice-fresh-pt-br"
    "jre-openjdk"
    "thunar"
    "feh"
    )
# -----------------------------------------------------------------------------
#
# Verificando e atualizando o sistema antes de começar a instalação
sudo pacman -Syuu
# -----------------------------------------------------------------------------
#
# Instalando pacotes
for package in "${packages[@]}" 
do
    sudo pacman -S "$package" --noconfirm --needed
done
# -----------------------------------------------------------------------------
