#! /bin/sh

# -----------------------------------------------------------------------------
# Autostart section
pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
"$HOME"/.config/polybar/launch.sh &
picom & #--experimental-backends &
        # usar experimental-backends para blur no terminal
nitrogen --restore &
screen &

# -----------------------------------------------------------------------------
# Configurações

bspc config border_width         1
bspc config window_gap          8

bspc config active_border_color #E84F4F
bspc config normal_border_color #D23D3D

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Spotify desktop='^5' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off